## combining chromosome SNP data per sample into WES SNP data

In [2]:
# set the paths
home = '/Users/mahtin'
home = '/Users/martinscience'
testdata = f"{home}/Dropbox/Icke/Work/somVar/testdata"
tooldata = f"{home}/Dropbox/Icke/Work/somVar/tooldata"
shell_path = "../shell"
static_path = f"{home}/Dropbox/Icke/Work/static"
bed_path = f"{static_path}/bed_files/SureSelect/hg38"

cnvdata = f"{tooldata}/myCNVdata/"
snp_path = f"{cnvdata}/cnv"
bedCov_path = f"{home}/mount/scratch/develop/PONcoverage/bedCov"
output_path = f"{cnvdata}/output"

In [3]:
snp_path

'/Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv'

In [4]:
test = pd.read_csv(f'{snp_path}/01_A.chr3.snp', sep='\t')
test[:13]

     Chr   Start  ExonPos Ref  Depth   Alt       VAF
0   chr3  197596       50   T    112    C1  0.008929
1   chr3  197682      136   T    197    G2  0.010152
2   chr3  328224      768   A    188    T1  0.005319
3   chr3  340795      950   T    348    A1  0.002874
4   chr3  340862     1017   C    536    G1  0.001866
5   chr3  342011     1209   G    160    A1  0.006250
6   chr3  342964     1360   C    179    A1  0.005587
7   chr3  343057     1453   G    236    T1  0.004237
8   chr3  344564     1484   C    119   T60  0.504202
9   chr3  344607     1527   G    192    T1  0.005208
10  chr3  344621     1541   C    206    A1  0.004854
11  chr3  349417     1662   A    127  G127  1.000000
12  chr3  354637     1838   C    161    A1  0.006211

### combine all snp for a sample into one df

In [7]:
# try with pd merge
import os
chrom_list = [f"chr{chrom + 1}" for chrom in range(22)] + ['chrX']
print(chrom_list)

def combine_heteroSNP(sample):
    snp_dfs = []
    file_base = os.path.join(snp_path, sample)
    for chrom in chrom_list:
        file = f"{file_base}.{chrom}.snp"
        if not os.path.isfile(file):
            continue
        print(f"Reading {chrom} of sample {sample} from {file}.")
        snp_df = pd.read_csv(file, sep='\t')
        snp_dfs.append(snp_df)
    snp_df = pd.concat(snp_dfs)
    return snp_df

['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrX']

In [9]:
snp_df = combine_heteroSNP("01_A")
snp_df.to_csv(f"{output_path}/01_A.snp.csv", sep='\t', index=False)
snp_df

Reading chr1 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr1.snp.
Reading chr2 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr2.snp.
Reading chr3 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr3.snp.
Reading chr4 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr4.snp.
Reading chr5 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr5.snp.
Reading chr6 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr6.snp.
Reading chr7 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr7.snp.
Reading chr8 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr8.snp.
Reading chr9 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr9.snp.
Reading chr10 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr10.snp.
Reading chr11 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr11.snp.
Reading chr12 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr12.snp.
Reading chr13 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr13.snp.
Reading chr14 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr14.snp.
Reading chr15 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr15.snp.
Reading chr16 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr16.snp.
Reading chr17 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr17.snp.
Reading chr18 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr18.snp.
Reading chr19 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr19.snp.
Reading chr20 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr20.snp.
Reading chr21 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr21.snp.
Reading chr22 of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chr22.snp.
Reading chrX of sample 01_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/01_A.chrX.snp.

       Chr      Start  ExonPos Ref  Depth  Alt       VAF
0     chr1      14930      836   A     64   G3  0.046875
1     chr1      15820      991   g     13  T11  0.846154
2     chr1      15903     1074   G     27   C4  0.148148
3     chr1      16949     1410   A    182   C7  0.038462
4     chr1      17365     1689   C    285  G40  0.140351
...    ...        ...      ...  ..    ...  ...       ...
9567  chrX  156023260  1835187   G     25  C22  0.880000
9568  chrX  156023266  1835193   C     25  T22  0.880000
9569  chrX  156024203  1835423   G     53   A7  0.132075
9570  chrX  156024239  1835459   C     56  G15  0.267857
9571  chrX  156024251  1835471   a     54   C6  0.111111

[350973 rows x 7 columns]

In [11]:
snp_df = combine_heteroSNP("03_A")
snp_df.to_csv(f"{output_path}/03_A.snp.csv", sep='\t', index=False)
snp_df

Reading chr1 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr1.snp.
Reading chr2 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr2.snp.
Reading chr3 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr3.snp.
Reading chr4 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr4.snp.
Reading chr5 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr5.snp.
Reading chr6 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr6.snp.
Reading chr7 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr7.snp.
Reading chr8 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr8.snp.
Reading chr9 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr9.snp.
Reading chr10 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr10.snp.
Reading chr11 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr11.snp.
Reading chr12 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr12.snp.
Reading chr13 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr13.snp.
Reading chr14 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr14.snp.
Reading chr15 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr15.snp.
Reading chr16 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr16.snp.
Reading chr17 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr17.snp.
Reading chr18 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr18.snp.
Reading chr19 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr19.snp.
Reading chr20 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr20.snp.
Reading chr21 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr21.snp.
Reading chr22 of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chr22.snp.
Reading chrX of sample 03_A from /Users/martinscience/Dropbox/Icke/Work/somVar/tooldata/myCNVdata//cnv/03_A.chrX.snp.

       Chr      Start  ExonPos Ref  Depth  Alt       VAF
0     chr1      14930      836   A     34   G5  0.147059
1     chr1      14933      839   G     34   A3  0.088235
2     chr1      15903     1074   G     22  C20  0.909091
3     chr1      16949     1410   A    258  C14  0.054264
4     chr1      17379     1703   G    355  A57  0.160563
...    ...        ...      ...  ..    ...  ...       ...
7106  chrX  156024239  1835459   C     53   G8  0.150943
7107  chrX  156024257  1835477   a     50   G1  0.020000
7108  chrX  156025055  1835538   C    154   G3  0.019481
7109  chrX  156025116  1835599   G    235  A63  0.268085
7110  chrX  156025135  1835618   C    253   A1  0.003953

[442423 rows x 7 columns]

### make a stacked "tidy version" of the coverage df for vizualisation in tidyverse

In [20]:
def tidy_df(df):
    return df.drop(columns=['Chr', 'Pos']).set_index('ExonPos').stack().reset_index().rename(columns={'level_1':'sample', 0:'Coverage'})

tidy_df(cov_df).to_csv(f"{output_path}/PON_coverage_tidy.csv", sep='\t', index=False)

### normalize the coverage to coverage 100

In [21]:
def normalize_coverage(cov_df):
    norm_df = cov_df.set_index(['Chr','Pos','ExonPos'])
    norm_df = norm_df / norm_df.mean() * 100
    return norm_df.reset_index()

In [22]:
norm_df = normalize_coverage(cov_df)
norm_df

,Chr,Pos,ExonPos,001_B,002_B,003_B,004_B,005_B,006_B,008_B,...,029_B,031_B,033_B,034_B,036_B,039_B,040_B,041_B,042_B,044_B
0,chr7,35350,967,4.033958,2.313776,3.922525,12.226485,0.703237,0.822889,7.261974,...,5.599328,7.034867,0.000000,3.480870,1.543389,3.009409,3.616486,6.796135,1.246768,0.697537
1,chr7,35400,1017,5.966553,2.006082,6.716224,16.196813,0.598537,0.954275,11.765672,...,8.207608,12.074771,0.000000,3.123285,1.334675,6.436252,7.599787,12.125656,1.186923,0.635850
2,chr7,35450,1067,6.240286,0.937251,7.195536,15.730204,0.253026,0.658657,13.479243,...,9.738675,13.865914,0.000000,1.620309,0.637129,7.829317,8.550406,12.945965,0.937569,0.412828
3,chr7,36200,1112,10.687931,0.099191,0.089993,0.106274,0.000000,9.805522,0.418307,...,0.000000,5.021375,0.000000,4.386008,6.327347,0.000000,0.000000,0.000000,0.000000,0.000000
4,chr7,36250,1162,11.035757,0.562756,0.187812,0.272327,0.000000,8.633423,0.630645,...,0.000000,3.674930,0.000000,4.821815,5.410101,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47121,chr7,159144650,2423334,97.903753,123.464123,118.808504,97.370181,58.180198,29.482259,77.985534,...,33.513945,46.211477,63.701295,67.930045,56.089291,57.901994,40.029333,34.920299,33.687667,39.555581
47122,chr7,159144700,2423384,79.199359,96.427563,93.923455,80.314873,47.497280,27.042979,61.554787,...,23.622164,35.779616,53.738247,50.492171,45.082345,51.378373,34.428946,29.734953,27.413931,30.876699
47123,chr7,159144750,2423434,62.985317,77.984159,76.333716,67.963848,37.822975,23.901824,50.477091,...,20.297563,27.954176,49.030637,39.814896,40.798204,49.407696,27.738447,26.165367,23.713525,25.671268
47124,chr7,159144800,2423484,47.057357,60.899062,62.846488,52.525897,29.954749,18.653311,41.645936,...,18.143134,18.504355,38.282988,32.562618,32.114580,44.670304,20.055998,22.178168,18.058186,17.837024
47125,chr7,159144850,2423534,30.131198,42.241082,46.864887,34.042533,21.392011,11.850644,28.570135,...,13.659298,10.320687,20.297505,20.885220,17.998884,29.958178,10.213990,16.316689,10.048949,10.548471

In [23]:
tidy_df(norm_df).to_csv(f"{output_path}/PON_coverage_normtidy.csv", sep='\t', index=False)

### compute the mean of all the coverages

In [25]:
def add_mean(norm_df):
    norm_df = norm_df.set_index(['Chr', 'Pos', 'ExonPos'])
    norm_df['meanCov'] = norm_df.mean(axis=1)
    norm_df['medianCov'] = norm_df.median(axis=1)
    norm_df['std'] = norm_df.std(axis=1)
    return norm_df.reset_index()
mean_df = add_mean(norm_df)
tidy_df(mean_df).to_csv(f"{output_path}/PON_coverage_mean.csv", sep='\t', index=False)
mean_df

,Chr,Pos,ExonPos,001_B,002_B,003_B,004_B,005_B,006_B,008_B,...,034_B,036_B,039_B,040_B,041_B,042_B,044_B,meanCov,medianCov,std
0,chr7,35350,967,4.033958,2.313776,3.922525,12.226485,0.703237,0.822889,7.261974,...,3.480870,1.543389,3.009409,3.616486,6.796135,1.246768,0.697537,3.085826,2.008443,3.093574
1,chr7,35400,1017,5.966553,2.006082,6.716224,16.196813,0.598537,0.954275,11.765672,...,3.123285,1.334675,6.436252,7.599787,12.125656,1.186923,0.635850,4.657405,2.006082,5.103127
2,chr7,35450,1067,6.240286,0.937251,7.195536,15.730204,0.253026,0.658657,13.479243,...,1.620309,0.637129,7.829317,8.550406,12.945965,0.937569,0.412828,4.844926,1.126427,5.745554
3,chr7,36200,1112,10.687931,0.099191,0.089993,0.106274,0.000000,9.805522,0.418307,...,4.386008,6.327347,0.000000,0.000000,0.000000,0.000000,0.000000,3.020992,0.223438,3.935328
4,chr7,36250,1162,11.035757,0.562756,0.187812,0.272327,0.000000,8.633423,0.630645,...,4.821815,5.410101,0.000000,0.000000,0.000000,0.000000,0.000000,2.711400,0.562756,3.431450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47121,chr7,159144650,2423334,97.903753,123.464123,118.808504,97.370181,58.180198,29.482259,77.985534,...,67.930045,56.089291,57.901994,40.029333,34.920299,33.687667,39.555581,61.920583,58.180198,24.678553
47122,chr7,159144700,2423384,79.199359,96.427563,93.923455,80.314873,47.497280,27.042979,61.554787,...,50.492171,45.082345,51.378373,34.428946,29.734953,27.413931,30.876699,49.407998,47.497280,19.564811
47123,chr7,159144750,2423434,62.985317,77.984159,76.333716,67.963848,37.822975,23.901824,50.477091,...,39.814896,40.798204,49.407696,27.738447,26.165367,23.713525,25.671268,41.184198,39.315711,15.846882
47124,chr7,159144800,2423484,47.057357,60.899062,62.846488,52.525897,29.954749,18.653311,41.645936,...,32.562618,32.114580,44.670304,20.055998,22.178168,18.058186,17.837024,32.596834,30.363157,13.023941
47125,chr7,159144850,2423534,30.131198,42.241082,46.864887,34.042533,21.392011,11.850644,28.570135,...,20.885220,17.998884,29.958178,10.213990,16.316689,10.048949,10.548471,21.131059,20.297505,9.650830

### filter the coverage

In [27]:
mean_df['std'].max()

464.98562510909875

In [36]:
def filter_coverage(df, mincov, maxstd):
    filter_df = df.query('meanCov > @mincov and std < @maxstd')
    return filter_df

In [38]:
filter_df = filter_coverage(mean_df, mincov=20, maxstd=50)
tidy_df(filter_df).to_csv(f"{output_path}/PON_coverage_filter.csv", sep='\t', index=False)